return { 
    plouffe_admin = '1.0.0', 
    plouffe_blips = '1.0.0', 
    plouffe_cayoloader = '1.0.0', 
    plouffe_cayorobbery = '1.0.0', 
    plouffe_doorlock = '1.0.0', 
    plouffe_drugs = '1.0.0', 
    plouffe_fleeca = '1.0.0', 
    plouffe_hud = '1.0.0', 
    plouffe_jail = '2.0.0', 
    plouffe_lib = '1.0.0', 
    plouffe_paletobank = '1.0.0', 
    plouffe_pedcontroller = '1.0.0', 
    plouffe_shopsrobbery = '1.0.0', 
    plouffe_status = '1.0.0', 
    plouffe_trainrobbery = '1.0.0', 
    plouffe_vangelico = '1.0.0', 
    plouffe_weapons = '1.0.0', 
}
